name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install huggingface_hub
        run: pip install huggingface_hub

      - name: Login to Hugging Face CLI
        run: echo "${{ secrets.HF_TOKEN }}" | huggingface-cli login --token

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push to Hugging Face Space
        run: |
          git remote add hf https://huggingface.co/spaces/Cinema4dArabic/cinema_4d_hub
          git push hf main --force
