name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main   # تابع الفرع main في هذا الريبو

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install huggingface_hub CLI
      run: pip install huggingface_hub

    - name: Login to Hugging Face CLI
      run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Clone Hugging Face Space repo
      run: git clone https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Cinema4dArabic/cinema_4d_hub

    - name: Copy files from main folder to Space repo
      run: |
        cp -r ./main/* ./cinema_4d_hub/

    - name: Commit and push to Space repo
      working-directory: ./cinema_4d_hub
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Auto deploy from GitHub main branch" || echo "No changes to commit"
        git push
