name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # أو الفرع الذي تستخدمه

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install huggingface_hub
        run: pip install huggingface_hub

      - name: Login to Hugging Face CLI
        run: echo "${{ secrets.HF_TOKEN }}" | huggingface-cli login --token

      - name: Push to Hugging Face Space
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote add space https://huggingface.co/spaces/Cinema4dArabic/cinema_4d_hub
          git push space HEAD:main --force
