name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Hugging Face CLI
        run: |
          pip install -U huggingface_hub

      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Login to Hugging Face
        run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      - name: Clone Hugging Face Space
        run: |
          git clone https://huggingface.co/spaces/Cinema4dArabic/cinema_4d_hub

      - name: Copy files to Space repo
        run: |
          cp -r ./* ./cinema_4d_hub/
          # استثناء ملفات git الخاصة بالspace لو حابب، مثلًا:
          rm -rf ./cinema_4d_hub/.git

      - name: Push to Hugging Face Space
        run: |
          cd cinema_4d_hub
          git add .
          git commit -m "Auto deploy from GitHub"
          git push
